const enum ENGRAM_TOKEN_TYPE {
	NONE,
	HEADING_1_MARKUP,
	HEADING_2_MARKUP,
	HEADING_3_MARKUP,
	UNORDERED_LIST_MARKUP,
	ORDERED_LIST_MARKUP,
	HORIZONTAL_RULE_MARKUP,
	IMAGE_MARKUP_1, IMAGE_MARKUP_2,
	LEFT_BOLD_TEXT_MARKUP, RIGHT_BOLD_TEXT_MARKUP,
	LEFT_ITALIC_TEXT_MARKUP, RIGHT_ITALIC_TEXT_MARKUP,
	LEFT_UNDERLINED_TEXT_MARKUP, RIGHT_UNDERLINED_TEXT_MARKUP,
	LEFT_HIGHLIGHTED_TEXT_MARKUP, RIGHT_HIGHLIGHTED_TEXT_MARKUP,
	LEFT_STRIKETHROUGH_TEXT_MARKUP, RIGHT_STRIKETHROUGH_TEXT_MARKUP,
	LINK_MARKUP_1, LINK_MARKUP_2, LINK_MARKUP_3
}

export default ENGRAM_TOKEN_TYPE;
