const HEADING_1_MARKUP_TOKEN = {
	name: 'HEADING 1 MARKUP',
	value: '=1= ',
};
const HEADING_2_MARKUP_TOKEN = {
	name: 'HEADING 2 MARKUP',
	value: '=2= ',
};
const HEADING_3_MARKUP_TOKEN = {
	name: 'HEADING 3 MARKUP',
	value: '=3= ',
};
const UNORDERED_LIST_MARKUP_TOKEN = {
	name: 'UNORDERED LIST MARKUP',
	value: '* ',
};
const HORIZONTAL_RULE_MARKUP_TOKEN = {
	name: 'HORIZONTAL RULE MARKUP',
	value: '--- ',
};
const IMAGE_MARKUP_1_TOKEN = {
	name: 'IMAGE MARKUP 1',
	value: 'image:',
};
const IMAGE_MARKUP_2_TOKEN = {
	name: 'IMAGE MARKUP 2',
	value: '{}',
};
const LEFT_BOLD_TEXT_MARKUP_TOKEN = {
	name: 'LEFT BOLD TEXT MARKUP',
	value: '`@',
};
const RIGHT_BOLD_TEXT_MARKUP_TOKEN = {
	name: 'RIGHT BOLD TEXT MARKUP',
	value: '@`',
};
const LEFT_ITALIC_TEXT_MARKUP_TOKEN = {
	name: 'LEFT ITALIC TEXT MARKUP',
	value: '`/',
};
const RIGHT_ITALIC_TEXT_MARKUP_TOKEN = {
	name: 'RIGHT ITALIC TEXT MARKUP',
	value: '/`',
};
const LEFT_UNDERLINED_TEXT_MARKUP_TOKEN = {
	name: 'LEFT UNDERLINED TEXT MARKUP',
	value: '`_',
};
const RIGHT_UNDERLINED_TEXT_MARKUP_TOKEN = {
	name: 'RIGHT UNDERLINED TEXT MARKUP',
	value: '_`',
};
const LEFT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = {
	name: 'LEFT HIGHLIGHTED TEXT MARKUP',
	value: '`=',
};
const RIGHT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = {
	name: 'RIGHT HIGHLIGHTED TEXT MARKUP',
	value: '=`',
};
const LEFT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = {
	name: 'LEFT STRIKETHROUGH TEXT MARKUP',
	value: '`-',
};
const RIGHT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = {
	name: 'RIGHT STRIKETHROUGH TEXT MARKUP',
	value: '-`',
};
const LINK_MARKUP_1_TOKEN = {
	name: 'LINK TEXT MARKUP 1',
	value: '`_',
};
const LINK_MARKUP_2_TOKEN = {
	name: 'LINK TEXT MARKUP 2',
	value: '_(',
};
const LINK_MARKUP_3_TOKEN = {
	name: 'LINK TEXT MARKUP 3',
	value: ')`',
};

export {
	HEADING_1_MARKUP_TOKEN, HEADING_2_MARKUP_TOKEN, HEADING_3_MARKUP_TOKEN, UNORDERED_LIST_MARKUP_TOKEN, HORIZONTAL_RULE_MARKUP_TOKEN, IMAGE_MARKUP_1_TOKEN, IMAGE_MARKUP_2_TOKEN, LEFT_BOLD_TEXT_MARKUP_TOKEN, RIGHT_BOLD_TEXT_MARKUP_TOKEN, LEFT_ITALIC_TEXT_MARKUP_TOKEN, RIGHT_ITALIC_TEXT_MARKUP_TOKEN, LEFT_UNDERLINED_TEXT_MARKUP_TOKEN, RIGHT_UNDERLINED_TEXT_MARKUP_TOKEN, LEFT_HIGHLIGHTED_TEXT_MARKUP_TOKEN, RIGHT_HIGHLIGHTED_TEXT_MARKUP_TOKEN, LEFT_STRIKETHROUGH_TEXT_MARKUP_TOKEN, RIGHT_STRIKETHROUGH_TEXT_MARKUP_TOKEN, LINK_MARKUP_1_TOKEN, LINK_MARKUP_2_TOKEN, LINK_MARKUP_3_TOKEN,
};
