"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BLANK_LINE_TOKEN = exports.LINK_MARKUP_3_TOKEN = exports.LINK_MARKUP_2_TOKEN = exports.LINK_MARKUP_1_TOKEN = exports.RIGHT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = exports.LEFT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = exports.RIGHT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = exports.LEFT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = exports.RIGHT_UNDERLINED_TEXT_MARKUP_TOKEN = exports.LEFT_UNDERLINED_TEXT_MARKUP_TOKEN = exports.RIGHT_ITALIC_TEXT_MARKUP_TOKEN = exports.LEFT_ITALIC_TEXT_MARKUP_TOKEN = exports.RIGHT_BOLD_TEXT_MARKUP_TOKEN = exports.LEFT_BOLD_TEXT_MARKUP_TOKEN = exports.IMAGE_MARKUP_2_TOKEN = exports.IMAGE_MARKUP_1_TOKEN = exports.HORIZONTAL_RULE_MARKUP_TOKEN = exports.UNORDERED_LIST_MARKUP_TOKEN = exports.HEADING_3_MARKUP_TOKEN = exports.HEADING_2_MARKUP_TOKEN = exports.HEADING_1_MARKUP_TOKEN = void 0;
const HEADING_1_MARKUP_TOKEN = {
    name: 'HEADING 1 MARKUP',
    value: '=1= ',
};
exports.HEADING_1_MARKUP_TOKEN = HEADING_1_MARKUP_TOKEN;
const HEADING_2_MARKUP_TOKEN = {
    name: 'HEADING 2 MARKUP',
    value: '=2= ',
};
exports.HEADING_2_MARKUP_TOKEN = HEADING_2_MARKUP_TOKEN;
const HEADING_3_MARKUP_TOKEN = {
    name: 'HEADING 3 MARKUP',
    value: '=3= ',
};
exports.HEADING_3_MARKUP_TOKEN = HEADING_3_MARKUP_TOKEN;
const UNORDERED_LIST_MARKUP_TOKEN = {
    name: 'UNORDERED LIST MARKUP',
    value: '* ',
};
exports.UNORDERED_LIST_MARKUP_TOKEN = UNORDERED_LIST_MARKUP_TOKEN;
const HORIZONTAL_RULE_MARKUP_TOKEN = {
    name: 'HORIZONTAL RULE MARKUP',
    value: '--- ',
};
exports.HORIZONTAL_RULE_MARKUP_TOKEN = HORIZONTAL_RULE_MARKUP_TOKEN;
const IMAGE_MARKUP_1_TOKEN = {
    name: 'IMAGE MARKUP 1',
    value: 'image:',
};
exports.IMAGE_MARKUP_1_TOKEN = IMAGE_MARKUP_1_TOKEN;
const IMAGE_MARKUP_2_TOKEN = {
    name: 'IMAGE MARKUP 2',
    value: '{}',
};
exports.IMAGE_MARKUP_2_TOKEN = IMAGE_MARKUP_2_TOKEN;
const LEFT_BOLD_TEXT_MARKUP_TOKEN = {
    name: 'LEFT BOLD TEXT MARKUP',
    value: '`@',
};
exports.LEFT_BOLD_TEXT_MARKUP_TOKEN = LEFT_BOLD_TEXT_MARKUP_TOKEN;
const RIGHT_BOLD_TEXT_MARKUP_TOKEN = {
    name: 'RIGHT BOLD TEXT MARKUP',
    value: '@`',
};
exports.RIGHT_BOLD_TEXT_MARKUP_TOKEN = RIGHT_BOLD_TEXT_MARKUP_TOKEN;
const LEFT_ITALIC_TEXT_MARKUP_TOKEN = {
    name: 'LEFT ITALIC TEXT MARKUP',
    value: '`/',
};
exports.LEFT_ITALIC_TEXT_MARKUP_TOKEN = LEFT_ITALIC_TEXT_MARKUP_TOKEN;
const RIGHT_ITALIC_TEXT_MARKUP_TOKEN = {
    name: 'RIGHT ITALIC TEXT MARKUP',
    value: '/`',
};
exports.RIGHT_ITALIC_TEXT_MARKUP_TOKEN = RIGHT_ITALIC_TEXT_MARKUP_TOKEN;
const LEFT_UNDERLINED_TEXT_MARKUP_TOKEN = {
    name: 'LEFT UNDERLINED TEXT MARKUP',
    value: '`_',
};
exports.LEFT_UNDERLINED_TEXT_MARKUP_TOKEN = LEFT_UNDERLINED_TEXT_MARKUP_TOKEN;
const RIGHT_UNDERLINED_TEXT_MARKUP_TOKEN = {
    name: 'RIGHT UNDERLINED TEXT MARKUP',
    value: '_`',
};
exports.RIGHT_UNDERLINED_TEXT_MARKUP_TOKEN = RIGHT_UNDERLINED_TEXT_MARKUP_TOKEN;
const LEFT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = {
    name: 'LEFT HIGHLIGHTED TEXT MARKUP',
    value: '`=',
};
exports.LEFT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = LEFT_HIGHLIGHTED_TEXT_MARKUP_TOKEN;
const RIGHT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = {
    name: 'RIGHT HIGHLIGHTED TEXT MARKUP',
    value: '=`',
};
exports.RIGHT_HIGHLIGHTED_TEXT_MARKUP_TOKEN = RIGHT_HIGHLIGHTED_TEXT_MARKUP_TOKEN;
const LEFT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = {
    name: 'LEFT STRIKETHROUGH TEXT MARKUP',
    value: '`-',
};
exports.LEFT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = LEFT_STRIKETHROUGH_TEXT_MARKUP_TOKEN;
const RIGHT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = {
    name: 'RIGHT STRIKETHROUGH TEXT MARKUP',
    value: '-`',
};
exports.RIGHT_STRIKETHROUGH_TEXT_MARKUP_TOKEN = RIGHT_STRIKETHROUGH_TEXT_MARKUP_TOKEN;
const LINK_MARKUP_1_TOKEN = {
    name: 'LINK TEXT MARKUP 1',
    value: '`_',
};
exports.LINK_MARKUP_1_TOKEN = LINK_MARKUP_1_TOKEN;
const LINK_MARKUP_2_TOKEN = {
    name: 'LINK TEXT MARKUP 2',
    value: '_(',
};
exports.LINK_MARKUP_2_TOKEN = LINK_MARKUP_2_TOKEN;
const LINK_MARKUP_3_TOKEN = {
    name: 'LINK TEXT MARKUP 3',
    value: ')`',
};
exports.LINK_MARKUP_3_TOKEN = LINK_MARKUP_3_TOKEN;
const BLANK_LINE_TOKEN = {
    name: 'BLANK LINE',
    value: '',
};
exports.BLANK_LINE_TOKEN = BLANK_LINE_TOKEN;
